---
title: "Talentmanagement in mittelständischen, und inhabergeführten Unternehmen erfolgreich einführen"
description: "Strategische Personalplanung initiiteren, umsetzen und als KMU davon profitieren."
date: 
author:
- name: Sebastian Sukstorf
  url: https://github.com/sebastiansukstorf
  affiliation: Sebastian Sukstorf - Consulting & Coaching
  affiliation_url: https://www.sebastian.sukstorf.de
  orcid_id: 0000-0002-1538-5658
citation_url: https://github.com/sebastiansukstorf/tmkmu
bibliography: sukstorf.bib
site: distill::distill_website

---

# Was meinen wir konkret, wenn wir über Talentmanagement sprechen

Talentmanagement ist ein großer Begriff.
Ein Blick nach [Wikipedia](https://de.wikipedia.org) hilft uns für eine erste Näherung zunächst weiter:

> "Talentmanagement bezeichnet die Gesamtheit personalpolitischer Maßnahmen in einer Organisation zur langfristigen Sicherstellung der Besetzung kritischer Rollen und Funktionen."^[vgl. @dewiki:204050263]

Aus der obigen Definition lassen sich die folgenden relevanten Punkte ableiten:

+ die Gesamtheit aller **personalpolitischen Maßnahmen** zur
+ langfristigen Sicherstellung von **Stellenbesetzungen** bei den
+ **kritischen Rollen** und Funktionen im Unternehmen

<aside>
Talentmangement sichert die Besetzung kritischer Funktionen für nachhaltigen Geschäftserfolg.
</aside>

Beim Talentmanagement geht es also darum, dass Unternehmen langfristig sicherstellen, ihre unternehmenskritischen Funktion in der einzelnen Funktionsbereich zu besetzen. 
Ein planvolles und strukturiertes Vorgehen ist hierbei sinnvoll.
Wer der geeignete Nachfolger oder die geeignete Nachfolgerin von unternehmenskritischen Positionen sein könnte, sollten sie nicht unbedingt dem Zufall überlassen.

Wer ist sofort, kurz-, mittel- oder langfristig für die kritische Position geeignet?
Wir werden uns im folgenden ansehen, welche Punkte hierfür berücksichtig werden sollten und wie sie diese erfolgreich innerhalb ihres Unternehmens umsetzen sollten.

